#!/usr/bin/env perl

use 5.014;
use strict;
use warnings;

use JSON::MaybeXS;

my $simulation = {
    turns => [
    ],
};

my $content = do {
    open my $f, "<", "simulation.org" or die "Can't open simulation.org: $!";
    local $/;
    scalar <$f>;
};

my @steps0;
while ($content =~ /^# TURN ([^\r\n]+)\R([^#]+)/gms) {
    push @steps0, {
        description => $1,
        content => $2,
    };
}

my $prev_turn_num;
for my $step0 (@steps0) {
    my ($turn_num, $turn_letter, $rest) = $step0->{description} =~ /(\d+)([ABCD]?)(.*)/
        or die "Can't parse description: $step0->{description}";
    $rest //= '';
    warn "DEBUG: description=<$step0->{description}>, turn_num=<$turn_num>, turn_letter=<$turn_letter>, rest=<$rest>\n" if $ENV{DEBUG};
    my $turn;
    if (!$prev_turn_num || $turn_num != $prev_turn_num) {
        # a new turn
        $turn = {steps=>[]};
        push @{$simulation->{turns}}, $turn;
    } else {
        $turn = $simulation->{turns}[-1];
    }
    $prev_turn_num = $turn_num;

    my @cards = grep {/\S/} split /^/m, $step0->{content};
    do { chomp; s/\|.+//; s/ \(.+//; } for @cards;

    my $step = {
        summary => '',
        moves => [],
    };

    if ($turn_num == 1) {
        $step->{summary} = "INITIAL DRAW";
        while (my ($c1, $c2) = splice @cards, 0, 2) {
            push @{$step->{moves}}, [$c1, DRAW => "P1"];
            push @{$step->{moves}}, [$c2, DRAW => "P2"];
        }
    } else {
        my ($from, $to);
        if ($turn_letter eq 'A') {
            $from = 'P1';
            $to = 'DISCARD';

            if ($rest =~ /PASS/) {
                $step->{summary} = "P1 PASSES";
                $step->{call} = "P1 PASSES";
                goto L1;
            }

            $rest =~ /(?:DISCARDS )?(\w+): ([^.]+)/ or die "Can't parse rest: $rest (description: $step0->{description})";
            $step->{summary} = "P1 DISCARDS $1: $2";
            $step->{call} = "P1 CALLS: $2";
            $step->{call} .= ". P1 WINS." if $rest =~ /WIN/;
        } elsif ($turn_letter eq 'B') {
            $from = 'DRAW';
            $to = 'P1';

            $step->{summary} = "P1 DRAWS ANOTHER 3 CARDS";
        } elsif ($turn_letter eq 'C') {
            $from = 'P2';
            $to = 'DISCARD';

            if ($rest =~ /PASS/) {
                $step->{summary} = "P2 PASSES";
                $step->{call} = "P2 PASSES";
                goto L1;
            }

            $rest =~ /(?:DISCARDS )?(\w+): ([^.]+)/ or die "Can't parse rest: $rest (description: $step0->{description})";
            $step->{summary} = "P2 DISCARDS $1: $2";
            $step->{call} = "P2 CALLS: $2";
            $step->{call} .= ". P2 WINS." if $rest =~ /WIN/;
        } elsif ($turn_letter eq 'D') {
            $from = 'DRAW';
            $to = 'P2';

            $step->{summary} = "P2 DRAWS ANOTHER 3 CARDS";
        } else {
            die "Unknown letter $turn_letter";
        }

      L1:

        for my $c (@cards) {
            push @{$step->{moves}}, [$c, $from, $to];
        }
    }

    push @{$turn->{steps}}, $step;
}

{
    open my $fh, ">", "simulation.json" or die "Can't open simulation.json for writing: $!";
    my $json = JSON::MaybeXS->new;
    $json->canonical->allow_nonref->pretty(1);
    print $fh $json->encode($simulation);
    close $fh;
}
